# Generated by Django 5.1.7 on 2026-09-30 11:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_phase1_connect'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='in_route_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='customer_contact',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='frozen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='frozen_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('contractor_assigned', 'Contractor Assigned'), ('contractor_in_route', 'Contractor In Route'), ('in_progress', 'Project In Progress'), ('ready_for_evaluation', 'Ready For Evaluation'), ('complete', 'Project Complete and Funds Disbursed')], default='created', max_length=40),
        ),
        migrations.CreateModel(
            name='SubJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending approval'), ('denied', 'Denied'), ('open', 'Open'), ('pending_review', 'Pending review'), ('accepted', 'Accepted')], default='pending_approval', max_length=20)),
                ('created_by', models.CharField(choices=[('client', 'Client'), ('contractor', 'Contractor')], max_length=20)),
                ('denial_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sub_jobs', to='tracker.contractor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_jobs', to='tracker.project')),
            ],
        ),
        migrations.CreateModel(
            name='SubJobPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='subjobs/%Y/%m/%d/')),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sub_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='before_photos', to='tracker.subjob')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('notes', models.TextField(blank=True, default='')),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('review_reason', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tracker.contractor')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('sub_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tracker.subjob')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('after', 'After'), ('evidence', 'Evidence')], default='after', max_length=20)),
                ('file', models.ImageField(upload_to='submissions/%Y/%m/%d/')),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tracker.submission')),
            ],
        ),
    ]
